spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/b14_technocenter
    #connection_url/db_name
    username: postgres
    password: palianganteng0401
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl: none
#        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  servlet:
    context-path: /user-service

jwt:
  secret-key: T&5^P6TZ4FHnqJIGQ,cKhW]4>-Yax^hagdq3417235gasdfasgd6S5a4s65X
